### ISSUE TITLE
Discovery / New Egg unlock

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [MrBacon470/Coop-Co#19]
![image](https://user-images.githubusercontent.com/627469/177122138-57844bcc-0c26-415d-94c8-5df396b79766.png)

Shouldn't it only get green when you reached the info about the new egg?

**Comment by VoidCloud04** [comment]
I would really have to look at how the progress bar is setup.

**Comment by VoidCloud04** [comment]
Alright I modified it for the next update so now yellow is progress to discovery and green is to unlock
