### ISSUE TITLE
[question] Is the game still being worked on?

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [MrBacon470/Coop-Co#26]
I'm having fun with it and I wanna know if i should be expecting the update to come out ever :)

**Comment by VoidCloud04** [comment]
I was going through a significant burn out for the last few months and been busy with college but yes development is resuming as of this message.

**Comment by ExplodingHairyPotatoCat** [comment]
> I was going through a significant burn out for the last few months and been busy with college but yes development is resuming as of this message.
I hope you're feeling better now!

**Comment by VoidCloud04** [comment]
Thank you I am!
