### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [MrBacon470/Coop-Co#31]
just looks like this upon loading 
![image](https://github.com/MrBacon470/Coop-Co/assets/101602826/c6ce596e-5900-4f68-95de-5654df2a6021)
(I am aware this seems to be an issue with trying to update it, I have no idea if this is helpful though.)
Clicking on the buttons doesn't work, and  I can scroll to the bottom. Hovering over the buttons highlights them but doesn't react to clicking

**Comment by VoidCloud04** [comment]
Yes the game is currently down due to deployment errors.

**Comment by VoidCloud04** [comment]
All Scripts & Images are failing to load to the game annoyingly enough

**Comment by ExplodingHairyPotatoCat** [comment]
Oh that sucks, any ideas as to why?

**Comment by VoidCloud04** [comment]
I'm trying to figure that out as both the official astro build action isn't working its just giving a 404 & the hacky solution gives me that problem

**Comment by VoidCloud04** [comment]
Currently Troubleshooting may end up taking a while to get it to work :/

**Comment by ExplodingHairyPotatoCat** [comment]
What if you tried renaming the page and then depoloying the astro build?

**Comment by VoidCloud04** [comment]
The problem is the github pages site fails to request the site itself then it gives a Content Security Policy Error

**Comment by VoidCloud04** [comment]
Should be finally fixed now
