### ISSUE TITLE
2.0 broke my game

### ISSUE THREAD

**Issue by dotbot123** [MrBacon470/Coop-Co#32]
went offline for a while in "the path", 2.0 removed it, prestiged, and now I  am  stuck with the debuffs and cant leave

HOW DO I FIX THIS

**Comment by VoidCloud04** [comment]
The path doesn't exist in game anymore so there isn't any debuffs affecting your save anymore please feel free to send a screenshot of the problem because I'm not understanding.

**Comment by VoidCloud04** [comment]
I found the issue source some old code that hadn't been removed after all this time
