### ISSUE TITLE
Tier I-V Automator doesn't work

### ISSUE THREAD

**Issue by osboz** [MrBacon470/Coop-Co#41]
Tier I-V Automator does nothing?
i dont really have much to say, just that nothing happens

![billede](https://github.com/MrBacon470/Coop-Co/assets/72261569/abd6bd88-5453-4520-b6bc-8dbcddd290fe)
![billede](https://github.com/MrBacon470/Coop-Co/assets/72261569/dab26494-b074-4a06-9466-9030f334be2a)

**Comment by osboz** [comment]
![billede](https://github.com/MrBacon470/Coop-Co/assets/72261569/13ab8c50-9fac-45e9-ad8b-e8154a806052)

**Comment by VoidCloud04** [comment]
Do you have enough money to purchase those upgrades?

**Comment by VoidCloud04** [comment]
Closed since no other information was given
