### ISSUE TITLE
Question. Whens next update?

### ISSUE THREAD

**Issue by MrBunnyBunn** [MrBacon470/Coop-Co#42]
Is this game still being worked on? I completed it and I had fun doing so.  Just wondering.

**Comment by VoidCloud04** [comment]
Life has taken me away from game development for the foreseeable future and the current state of the game was something I was satisfied with. So anyone can feel free to make forks but I personally don't see myself updating this anymore.

**Comment by MrBunnyBunn** [comment]
@MrBacon470 
Thank you, it was a good game, I hope you have luck with whatever you are doing now

**Comment by VoidCloud04** [comment]
I appreciate it! I am glad you enjoyed it.
